config/routes.rb
Rails.application.routes.draw do
  root "users#new"
  resources :posts do
    collection do
      post :confirm
    end
  end

  resources :users, only: [:new, :create, :edit, :update, :show, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :favorites, only: [:create, :destroy, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
mount_uploader :image, ImageUploader
belongs_to :user
validates :image, presence: true
validates :user_id, presence: true
has_many :favorites, dependent: :destroy
has_many :favorite_users, through: :favorites, source: :user
end

app/models/user.rb
class User < ApplicationRecord
    mount_uploader :image, ImageUploader
    before_validation { email.downcase! }
    validates :name,  presence: true, length: { maximum: 30 }
     validates :email, presence: true, length: { maximum: 255 },
                       format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
                       has_secure_password
                         validates :password, presence: true, length: { minimum: 6 }
    has_many :posts, dependent: :destroy
    has_many :favorites, dependent: :destroy
    end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
      include SessionsHelper
      before_action :login_required
    private
    def login_required
      redirect_to new_session_path unless current_user
    end
  end
  

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
     favorite = current_user.favorites.create(post_id: params[:post_id])

     redirect_to posts_path, notice: "#{favorite.post.user.name}'s post has been added to favorites"
   end
   def destroy
     favorite = current_user.favorites.find_by(id: params[:id]).destroy

     redirect_to posts_path, notice: "#{favorite.post.user.name}Unposted post"
   end
   def index

      @favorites = current_user.favorites
 end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action:logged_in?, only:[:new,:create]
   before_action :ensure_correct_user, only: [:edit, :update, :destroy]
  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show

    @favorite = current_user.favorites.find_by(post_id: @post.id)
  end

  # GET /posts/new
  def new
    if params[:back]
    @post = Post.new(post_params)
  else
    @post = current_user.posts.build
    @user = @post.user
  end
end

  # GET /posts/1/edit
  def edit
    @user = @post.user
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        PostMailer.post_mail(@post).deliver
        format.html { redirect_to post_path @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def confirm
    @post = current_user.posts.build(post_params)
    @user = @post.user
      render :new if @post.invalid?
    end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    @user = @post.user
      if @post.update(post_params)
        format.html { redirect_to_post_path @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @user=@post.user_id
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_post
  @post = Post.find(params[:id])
  end

    # Only allow a list of trusted parameters through.
  def post_params
  params.require(:post).permit(:caption, :image, :image_cache)
  end

  def ensure_correct_user
  @post = Post.find(params[:id])
  if current_user.id !=@post.user_id
  flash[:notice] = "No permission"
  redirect_to_post_path
end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def new
   end
  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      flash.now[:danger] = 'Login failed'
      render :new
    end
   end
  def destroy
     session.delete(:user_id)
     flash[:notice] = 'Logged out'
     redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: %i[ show edit update destroy ]
   skip_before_action :login_required, only: [:new, :create]
before_action :logged_in?, only: [:edit, :update, :delete]
before_action :own_user, only: [:edit, :update, :destroy]
    # GET /posts or /posts.json
    def index
      @user = User.all
    end

    def new
      @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save

          redirect_to user_path(@user), notice: "Account was successfully created"
        else
          render :new
        end
      end

      def show
        #@users = User.all
        @user = User.find(params[:id])
        # @posts =@user.posts
      #  @favorite_photos = @user.favorite_photos
      end

      def edit
              @user = User.find(params[:id])
      end
      def update
        @user = User.find(params[:id])
        if @user.update(user_params)
          redirect_to show, notice: "Edited  "
        else
          render :edit
        end
        end
      private
      def set_user
      @user = User.find(params[:id])
      end
      def user_params
      params.require(:user).permit(:name, :email, :password,
                                     :password_confirmation, :image, :image_cache)
      end
      def own_user
      if current_user.id != @user.id
      redirect_to user_path
    end
  end
    end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def choose_new_or_edit
      if action_name == 'new' || action_name == 'confirm' || action_name == 'create' || action_name =='show'
        confirm_posts_path
      elsif action_name == 'edit'
        post_path
      end
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
      current_user.present?

    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/create.html.erb
<h1>Favorites#create</h1>
<p>Find me in app/views/favorites/create.html.erb</p>

app/views/favorites/destroy.htmml.erb
h1>Favorites#destroy</h1>
<p>Find me in app/views/favorites/destroy.html.erb</p>

app/views/favorites/index.html.erb
<h1>Favorites list</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Content</th>
    <th>post</th>
  </tr>
  <tr>
    <% @favorites.each do |favorite| %>
    <td><%= favorite.post.user.name %></td>
    <td><%= favorite.post.caption %></td>
    <td><%= image_tag favorite.post.image.url %></td>
  </tr>
<% end %>
</table>

  <%= link_to 'Back', posts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstagramClone</title>
    <%= csrf_meta_tags %>
       <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<nav class="navbar navbar-expand-sm bg-danger navbar-dark">
<a class="navbar-brand" href="#">


<header>
    <div>
      <h1 class="Insta">Share your moments with the world ♬</h1>
   </div>
  </header>
</nav>

  <body>
    <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <% if logged_in? %>
    <%= link_to "Profile", user_path(current_user.id) %>
     <%= link_to " New Post", new_post_path %>
    <%= link_to "Log Out", session_path(current_user.id), method: :delete %>
    <%= link_to "Posts", posts_path %>


    <% else %>
    <%= link_to "Sign Up", new_user_path %>
    <%= link_to "Log In", new_session_path %>
    <% end %>
    <%= yield %>
    <footer>
      <p> Photosharing by Cw</p>
      </footer>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: @post, local: true ,url: choose_new_or_edit ) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <ul class="row">
     <li class = "col-sm-6 col-md-3"><%= form.label :caption %>
    <%= form.text_field :caption %></li>
  </div>

  <div class="field">
    <ul class="row">
   <li class = "col-sm-6 col-md-3">  <%= form.label :image %>
    <%= image_tag(@post.image.url) if @post.image && @post.image.url %>
    <%= form.file_field :image %>
     <%= form.hidden_field :image_cache %></li>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/confirm.html.erb
h3> Do you want to post the following content?</h3>

<%= form_with(model: @post,url: posts_path, local: true) do |form| %>
  <%= form.hidden_field :caption %>
  <p>
    <%= @post.caption %>
  </p>
  <%= image_tag(@post.image.url) if @post.image && @post.image.url %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit "To post" %>
<% end %>
<%= form_with(model:@post, url: new_post_path, local:true, method:"get") do |form| %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit "Return", name: "back" %>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <h1 class="title">Photoclone</h1>
    <nav class="menu">
      <ul>
        <li class="col-md-4"><%= link_to "New Post", new_post_path(@post) %></li>
        <li class="col-md-4">Sign out</li>
      </ul>
    </nav>
<table>


  <tbody>
    <% @posts.each do |post| %>
      <tr>
            <td><%= post.user.name %></td>
        <td><%= post.caption %></td>
        <td><%= image_tag post.image.url %></td>
        <td><%= link_to 'Show', post %></td>

        <% if current_user.id == post.user.id %>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= image_tag @post.image.url %>
</p>

<p>
  <strong>Caption:</strong>
  <%= @post.caption %>
</p>
<% unless @post.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'Remove favorite', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'Favorite', favorites_path(post_id: @post.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>
<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

 <% if @user.errors.any? %>
 <div id="error_explanation">
 <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
 <ul>
 <% @user.errors.full_messages.each do |message| %>
 <li><%= message %></li>
 <% end %>
 </ul>
 </div>
 <% end %>
 <%= form_with(model: @user, local: true) do |f| %>

      <div class="field">
        <ul class="row">
          <li class = "col-sm-6 col-md-3"><%= f.label :name %>
      <%= f.text_field :name %></li><br>
         <li class = "col-sm-6 col-md-3"><%= f.label :email %>
      <%= f.email_field :email %></li><br>
          <li class = "col-sm-6 col-md-3"><%= f.label :password %>
      <%= f.password_field :password %></li><br>
          <li class = "col-sm-6 col-md-3"> <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %></li><br>
          <li class = "col-sm-6 col-md-3"> <%= f.label :image %>
      <%= f.file_field :image %></li><br>

 <%= f.submit "Save changes" %>
 <% end %>

app/views/users/new.html.erb
<h1>Sign up :)</h1>
 <% if @user.errors.any? %>
 <div id="error_explanation">
 <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
 <ul>
 <% @user.errors.full_messages.each do |message| %>
 <li><%= message %></li>
 <% end %>
 </ul>
 </div>
 <% end %>
 <%= form_with(model: @user, local: true) do |f| %>

      <div class="field">
        <ul class="row">
          <li class = "col-sm-6 col-md-3"><%= f.label :name %>
      <%= f.text_field :name %></li><br>
         <li class = "col-sm-6 col-md-3"><%= f.label :email %>
      <%= f.email_field :email %></li><br>
          <li class = "col-sm-6 col-md-3"><%= f.label :password %>
      <%= f.password_field :password %></li><br>
          <li class = "col-sm-6 col-md-3"> <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %></li><br>
          <li class = "col-sm-6 col-md-3"> <%= f.label :image %>
      <%= f.file_field :image %></li><br>

 <%= f.submit "Create my account" %>
 <% end %>

app/views/users/show.html.erb
<% if logged_in? %>
<h1><%= @user.name %></h1>
<p>

  <%= image_tag @user.image.url %>
</p>

<% if current_user.id == @user.id %>
    <%= link_to 'Favorites List', favorites_path %> |
    <%= link_to 'Edit profile', edit_user_path(@user) %>
  <% end %>
<% else %>
  <h1>user：<%= @user.name %></h1>
  <h3><%= link_to "Log in", new_session_path %>please</h3>
<% end %>